server:
  port: ":8080"

jwt:
  secret: "my-super-secret-gateway-key"

# dynamic route table
routes:
  # 鉴权和抽奖业务 -> 指向 Interaction 服务 (8082)
  - path_prefix: "/api/v1/auth"
    target_url: "http://localhost:8082"
  - path_prefix: "/api/v1/lottery"
    target_url: "http://localhost:8082"
    
  # 上传业务 -> 指向 Storage 服务 (8083)
  - path_prefix: "/api/v1/upload"
    target_url: "http://localhost:8083"
    
  # 如果后续有 compute 业务
  - path_prefix: "/api/v1/compute"
    target_url: "http://localhost:8084"