version: '3.8'

services:
  # 1. 数据库服务
  mysql:
    image: mysql:8.0
    container_name: compute-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cloud_compute
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  # 2. 消息队列服务
  rabbitmq:
    image: rabbitmq:3-management  # 关键：带 management 后缀才有网页后台
    container_name: compute-rabbitmq
    restart: always
    ports:
      - "5672:5672"   # 你的代码连接这个端口 (App)
      - "15672:15672" # 浏览器访问这个端口 (Web UI)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mysql_data:
  rabbitmq_data: